{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "dh5w3icrlwkxt"
  },
  "info": {
    "title": "SMSC-Tracker_v.1.0.0",
    "version": "1.0",
    "description": "SMSC Tracker API's to get details of SMS submitted, delivery attempts and SMS content",
    "contact": {
      "name": "Tayana Mobility Technologies",
      "url": "http://www.tayanamobility.com",
      "email": "mailto:sast@tayana.in"
    },
    "license": {
      "name": "Tayana Proprietary License",
      "url": "http://www.tayanamobility.com/license"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/smsc/v1.0/getSubmitInfo": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SubmitInfo"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "MessageReference": "string",
                      "scts": "string",
                      "Source": "string",
                      "Destination": "string",
                      "SenderId": "string",
                      "DCS": 0,
                      "ContentLength": "string",
                      "Validity": "string",
                      "Type": 0,
                      "DSR": true,
                      "IMSI": "string",
                      "VMSC": "string",
                      "ConcatInfo": "string",
                      "ProtocolId": "string",
                      "Priority": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-smsc-v1.0-submit",
        "security": [
          {
            "SMSC-Basic-Authorization": []
          }
        ]
      },
      "parameters": []
    },
    "/smsc/v1.0/getSmsInfo": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SmsInfo"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "MessageReference": "string",
                      "scts": "string",
                      "Source": "string",
                      "Destination": "string",
                      "DCS": 0,
                      "Content": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-smsc-v1.0-sms",
        "security": [
          {
            "SMSC-Basic-Authorization": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "messageReference",
            "description": "MessageReference received from getSubmitInfo"
          }
        ]
      },
      "parameters": []
    },
    "/smsc/v1.0/getDeliverInfo": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "submitInfo": {
                      "$ref": "#/components/schemas/SubmitInfo"
                    },
                    "deliverDetails": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/DeliverInfo"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "submitInfo": {
                        "MessageReference": "string",
                        "scts": "string",
                        "Source": "string",
                        "Destination": "string",
                        "SenderId": "string",
                        "DCS": 0,
                        "ContentLength": "string",
                        "Validity": "string",
                        "Type": 0,
                        "DSR": true,
                        "IMSI": "string",
                        "VMSC": "string",
                        "ConcatInfo": "string",
                        "ProtocolId": "string",
                        "Priority": "string"
                      },
                      "deliverDetails": [
                        {
                          "MessageReference": "string",
                          "scts": "string",
                          "Source": "string",
                          "Destination": "string",
                          "DCS": 0,
                          "ContentLength": "string",
                          "Validity": "string"
                        }
                      ]
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "submitInfo": {
                      "$ref": "#/components/schemas/SubmitInfo"
                    },
                    "deliverInfo": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/DeliverInfo"
                      }
                    }
                  }
                },
                "examples": {}
              },
              "multipart/form-data": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "submitInfo": {
                      "$ref": "#/components/schemas/SubmitInfo"
                    },
                    "deliverInfo": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/DeliverInfo"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "submitInfo": {
                        "MessageReference": "string",
                        "scts": "string",
                        "Source": "string",
                        "Destination": "string",
                        "SenderId": "string",
                        "DCS": 0,
                        "ContentLength": "string",
                        "Validity": "string",
                        "Type": 0,
                        "DSR": true,
                        "IMSI": "string",
                        "VMSC": "string",
                        "ConcatInfo": "string",
                        "ProtocolId": "string",
                        "Priority": "string"
                      },
                      "deliverInfo": [
                        {
                          "MessageReference": "string",
                          "scts": "string",
                          "Source": "string",
                          "Destination": "string",
                          "DCS": 0,
                          "ContentLength": "string",
                          "Validity": "string"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-smsc-v1.0-sms",
        "security": [
          {
            "SMSC-Basic-Authorization": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "messageReference",
            "description": "MessageReference received from getSubmitInfo"
          }
        ]
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "DeliverInfo": {
        "title": "deliverInfo",
        "x-stoplight": {
          "id": "gfl1csv9bmwwo"
        },
        "type": "object",
        "description": "Details of SMS delivery Attempts for the requested message reference",
        "examples": [
          {
            "MessageReference": "string",
            "scts": "string",
            "Source": "string",
            "Destination": "string",
            "DCS": 0,
            "ContentLength": "string",
            "Validity": "string"
          }
        ],
        "properties": {
          "Attempt": {
            "type": "integer"
          },
          "Time": {
            "type": "string",
            "description": "Format \"yyyy-MM-dd HH:mm:ss\""
          },
          "destIMSI": {
            "type": "string"
          },
          "destVMSC": {
            "type": "string"
          },
          "Status": {
            "type": "string"
          },
          "Reason": {
            "type": "string"
          }
        }
      },
      "SmsInfo": {
        "title": "smsInfo",
        "x-stoplight": {
          "id": "e3t3ng9bwxa2w"
        },
        "type": "object",
        "description": "Sms Content for the requested message reference",
        "examples": [
          {
            "MessageReference": "string",
            "scts": "string",
            "Source": "string",
            "Destination": "string",
            "DCS": 0,
            "Content": "string"
          }
        ],
        "properties": {
          "MessageReference": {
            "type": "string"
          },
          "scts": {
            "type": "string",
            "description": "Format \"yyyy-MM-dd HH:mm:ss\""
          },
          "Source": {
            "type": "string",
            "minLength": 6,
            "maxLength": 15
          },
          "Destination": {
            "type": "string"
          },
          "DCS": {
            "type": "integer",
            "minimum": 0,
            "maximum": 255
          },
          "Content": {
            "type": "string"
          }
        },
        "required": [
          "MessageReference",
          "scts",
          "Source",
          "Destination",
          "DCS",
          "Content"
        ]
      },
      "SubmitInfo": {
        "title": "submitInfo",
        "x-stoplight": {
          "id": "v7h2zy5tmrp82"
        },
        "type": "object",
        "description": "Details of Messages submitted to SMSC",
        "properties": {
          "MessageReference": {
            "type": "string"
          },
          "scts": {
            "type": "string",
            "description": "Format \"yyyy-MM-dd HH:mm:ss\""
          },
          "Source": {
            "type": "string"
          },
          "Destination": {
            "type": "string"
          },
          "SenderId": {
            "type": "string"
          },
          "DCS": {
            "type": "integer"
          },
          "ContentLength": {
            "type": "string"
          },
          "Validity": {
            "type": "string",
            "description": "Format \"yyyy-MM-dd HH:mm:ss\""
          },
          "Type": {
            "type": "integer"
          },
          "DSR": {
            "type": "boolean"
          },
          "IMSI": {
            "type": "string"
          },
          "VMSC": {
            "type": "string"
          },
          "ConcatInfo": {
            "type": "string"
          },
          "ProtocolId": {
            "type": "string"
          },
          "Priority": {
            "type": "string"
          }
        },
        "required": [
          "MessageReference",
          "scts",
          "Source",
          "Destination",
          "SenderId",
          "DCS",
          "ContentLength",
          "Validity",
          "Type",
          "DSR"
        ],
        "examples": [
          {
            "MessageReference": "string",
            "scts": "string",
            "Source": "string",
            "Destination": "string",
            "SenderId": "string",
            "DCS": 0,
            "ContentLength": "string",
            "Validity": "string",
            "Type": 0,
            "DSR": true,
            "IMSI": "string",
            "VMSC": "string",
            "ConcatInfo": "string",
            "ProtocolId": "string",
            "Priority": "string"
          }
        ]
      }
    },
    "securitySchemes": {
      "SMSC-Basic-Authorization": {
        "type": "http",
        "scheme": "basic"
      }
    }
  }
}
